# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2aba730096c7cea71208d5260dee0ba9"
application_url = "https://macroforge-9jyq.onrender.com"
embedded = true
name = "macroforge-public"

[webhooks]
api_version = "2026-10"

[[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  topics = ["orders/create"]
  uri = "/webhooks/orders/create"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_discounts,write_metaobject_definitions,write_metaobjects,write_products"

[auth]
redirect_urls = [
  "https://macroforge-9jyq.onrender.com/auth/callback",
  "https://macroforge-9jyq.onrender.com/auth/exit-iframe"
]

[app_proxy]
url = "https://macroforge-9jyq.onrender.com"
subpath = "macroforge"
prefix = "apps"

[build]
automatically_update_urls_on_dev = true
